apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-eks-irsa
spec:
  packagePullPolicy: Always
  crossplane:
    version: ">=v1.12.1-up.2"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.35.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.15.0"
